org.tutorial.first_extension: # {group_id}.{name} from the knime.yml
  src: /Users/pfeuffer/git/knime_python_nodes/tutorial_extension # Path to folder containing the extension files
  conda_env_path: /Users/pfeuffer/miniconda3/envs/pyopenms # Path to the Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform